project/apps/Home/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.login_request, name="login"),
    path('logout/', LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path('about/', TemplateView.as_view(template_name="Home/about.html"), name="about"),
    path('register/', views.register, name="register"),

]

urlpatterns += staticfiles_urlpatterns()

project/apps/Producto/urls.py
from django.urls import path

from . import views

app_name = "Producto"

urlpatterns = [path("", views.index, name="home")]

urlpatterns += [
    path("ubicacion/list/", views.UbicacionList.as_view(), name="ubicacion_list"),
    path("ubicacion/create/", views.UbicacionCreate.as_view(), name="ubicacion_create"),
    path("ubicacion/detail/<int:pk>", views.UbicacionDetail.as_view(), name="ubicacion_detail"),
    path("ubicacion/update/<int:pk>", views.UbicacionUpdate.as_view(), name="ubicacion_update"),
    path("ubicacion/delete/<int:pk>", views.UbicacionDelete.as_view(), name="ubicacion_delete"),
]

urlpatterns += [
    path("cilindro/list/", views.CilindroList.as_view(), name="cilindro_list"),
    path("cilindro/create/", views.CilindroCreate.as_view(), name="cilindro_create"),
    path("cilindro/detail/<int:pk>", views.CilindroDetail.as_view(), name="cilindro_detail"),
    path("cilindro/update/<int:pk>", views.CilindroUpdate.as_view(), name="cilindro_update"),
    path("cilindro/delete/<int:pk>", views.CilindroDelete.as_view(), name="cilindro_delete"),
]

urlpatterns += [
    path("salida/list/", views.CilindroList.as_view(), name="salida_list"),
    path("salida/create/", views.CilindroCreate.as_view(), name="salida_create"),
    path("salida/detail/<int:pk>", views.CilindroDetail.as_view(), name="salida_detail"),
    path("salida/update/<int:pk>", views.CilindroUpdate.as_view(), name="salida_update"),
    path("salida/delete/<int:pk>", views.CilindroDelete.as_view(), name="salida_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("Producto/", include("Producto.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/Home/models.py
from django.db import models

# Create your models here.

project/apps/Home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        # Quita los mensajes de ayuda
        # help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/apps/Home/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse
from django.http.request import HttpRequest
from django.shortcuts import render

from . import forms


def home(request):
    return render(request, "Home/index.html")


def login_request(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "Home/index.html", {"mensaje": "Inició sesión correctamente"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "Home/login.html", {"form": form})


@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "Home/index.html", {"mensaje": "Usuario creado"})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "Home/register.html", {"form": form})

project/apps/Home/templates/Home/about.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Nosotros
{% endblock %}

{% block INDEX_CONTENIDO %}
    <div class="text-center display-10 mb-sm-1  mt-1">
        En Escogas nos apoyamos en la calidad de nuestros profesionales y en la competitividad de nuestras operaciones para acompañar a nuestros clientes en su desarrollo ofreciéndoles soluciones sostenibles e innovadoras adaptadas a sus necesidades.

        Nuestras principales áreas de trabajo son el rubro de los gases y servicios relacionados tanto del sector industrial (soldadura, gran minería, pulpa y papel, alimentos, Alphagaz, piscicultura) como del medicinal (clínicas, hospitales, servicio de oxigenoterapia domiciliaria, etc.). La satisfacción total de las necesidades y expectativas de nuestros clientes es nuestro compromiso y base fundamental del futuro éxito de nuestras operaciones. Escogas es y será un socio para sus clientes, empleados y accionistas
    </div>
{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Inventario Cilindros</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/favicon.ico' %} " />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'Home/navbar.html' %}
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">

            {% block BASE_CONTENIDO %}
                
                        
            {% endblock BASE_CONTENIDO %}
            
            
        </div>
        <!-- Footer-->
        {% include 'Home/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src=  " {% static 'Home/js/scripts.js' %}" ></script>
    </body>
</html>

project/apps/Home/templates/Home/contacto.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Contáctanos
{% endblock %}

{% block INDEX_CONTENIDO %}
    <div class="text-center display-10 mb-sm-1  mt-1">
        Dirección: Francisco Javier 456, Comuna Quinta Normal.
        Santiago, Región Metropolitana
        Téléfono: 99999999
        E-mail:ventasescogas.cl
    </div>
{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/footer.html
<footer class="bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Sitio de Alejandra Caicedo - 2023</p></div>
</footer>

project/apps/Home/templates/Home/index.html
{% extends 'Home/base.html' %}
{% load static %}

{% block BASE_CONTENIDO %}

    <div class="row align-items-center my-5">
        <h1 class="pb-lg-3 text-bg-light">

    {% block INDEX_TITULO %}
    Inicio
    {% endblock INDEX_TITULO %}
        </h1>
    </div>

    {% block INDEX_CONTENIDO %}
        {% if user.is_authenticated %}
            {{ mensaje }}
            <h3> Bienvenido {{ user.username }}</h3>
        {% endif %}

        {% if user.is_staff %}
            <div class="row">
                <a href="{% url 'admin:index' %}" class="btn btn-outline-dark">Panel de Administración</a>
            </div>
            <div class="row">
                <a href="{% url 'Home:register' %}" class="btn btn-outline-dark">Registrar nuevo usuario</a>
            </div>
        {% endif %}
    
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'Home/img/escogas.jpg' %}"  alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">ESCOGAS SPA</h1>
            <p> Empresa dedicada a la distribución de gases industriales</p>
            
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-10 py-8 text-center">
        <div class="card-body"><p class="text-white m-0">Nuestros Productos</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        
        {% include 'Home/info.html' %}
        
        
        
    </div>    
    {% endblock INDEX_CONTENIDO %}
    
    {% endblock BASE_CONTENIDO %}

project/apps/Home/templates/Home/index_back.html
<div class="d-grid gap-3 "> 
    <a href="{% url 'Home:home' %}" class="btn btn-info">Ir al menú principal</a>
</div>

project/apps/Home/templates/Home/info.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Argón</h2>
            <p class="card-text">Escogas suministra argón y mezclas de argón en distintos volúmenes y niveles de pureza. El argón se utiliza como atmósfera protectora en numerosos procesos industriales, incluyendo la fabricación de acero, la soldadura y otros procesos metalúrgicos, la fabricación de piezas electrónicas y de automoción, la conservación de alimentos y la elaboración de vino. El argón se utiliza también en aplicaciones de iluminación fluorescente y sirve de protector térmico no reactivo en ventanas con doble cristal.

                El argón puro y las mezclas de argón se utilizan comúnmente en procesos de arco eléctrico para soldar aluminio, acero inoxidable, bronce y cobre. Cuando se utiliza como gas de respaldo en aplicaciones de soldadura por arco, gas de respaldo o corte por plasma, el argón proporciona una atmósfera inerte para impedir la oxidación u otros cambios químicos que serían perjudiciales para la soldadura. En la fabricación de acero, el argón impide la interacción entre el metal líquido y la atmósfera circundante. Air Liquide ofrece argón puro y mezclas de gases de la marca ARCAL™ con cuatro productos listos para soldar, que engloban prácticamente cualquier aplicación de soldadura. Todos están diseñados para ser sencillos de utilizar, fiables y eficaces, en cualquier lugar y en cualquier momento.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más información</a></div>
    </div>
</div>
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Nitrogeno</h2>
            <p class="card-text">Suministramos Nitrógeno líquido y gaseoso a cualquier sector. Por ejemplo, las refinerías y plantas petroquímicas requieren grandes volúmenes de nitrógeno gaseoso para la purga de oxígeno y la humectación en operaciones de protección. El sector de los alimentos y las bebidas requiere cantidades variables de nitrógeno tanto líquido como gaseoso para aplicaciones de procesamiento y envasado alimentario y para ayudar a mantener temperaturas seguras cuando se almacenan y transportan los productos alimentarios.

                En muchos sectores, el nitrógeno se utiliza en cantidades más pequeñas para poner a cero y purgar instrumentos analíticos. Existen distintas clases de gases especializados de alta pureza disponibles para satisfacer muchos requisitos normativos y diluirlos para la realización de pruebas de emisiones de motores.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más información</a></div>
    </div>
</div>
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Oxígeno</h2>
            <p class="card-text">El oxígeno es esencial para muchos sectores. En el sector químico, el oxígeno de clase industrial se utiliza para mejorar un gran número de procesos petroquímicos. El oxígeno se utiliza en aplicaciones metalúrgicas como la fundición, el corte y la soldadura. Aumenta la eficiencia en una serie de procesos reduciendo la cantidad de combustible utilizado, así como las emisiones de dióxido de carbono. En el sector sanitario, el oxígeno médico se utiliza para tratar insuficiencias respiratorias, envenenamiento por monóxido de carbono y en tareas de reanimación.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más información</a></div>
    </div>
</div>
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">Dióxido de Carbono (CO2)</h2>
            <p class="card-text">El dióxido de carbono (CO2) sirve para una serie de aplicaciones clave en distintos sectores. En estado sólido (-78°C), el dióxido de carbono, también conocido como hielo seco, es una fuente de frío que se puede utilizar como fluido criogénico para procesos como la ultra congelación para conservación de tejidos y la extinción de incendios, ya que es no combustible. El dióxido de carbono emitido a la atmósfera por las actividades químicas y, de petróleo y gas, puede capturarse y purificarse para su uso en muchos sectores y aplicaciones distintas.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más información</a></div>
    </div>
</div>     
    

project/apps/Home/templates/Home/login.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Login
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3"> 
            <button type="submit" class="btn btn-success">Iniciar sesión</button>
        </div>
    </form>

{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/logout.html
{% extends 'Home/index.html' %}

{% block INDEX_CONTENIDO %}
    <div class="fs-3 fst-italic ">
        <p>Has cerrado sesión</p>
    </div>
{% endblock %}

project/apps/Home/templates/Home/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Escogas SpA - Control de Cilindros</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == "/" %} active {% endif %}" aria-current="page" href="{% url 'Home:home' %}">Inicio</a></li>
             
                {% if user.is_authenticated %}

                <li class="nav-item"><a class="nav-link {% if request.path == "/Producto/" %} active  {% endif %}" href="{% url 'Producto:home' %}">Cilindros</a></li>
                <li class="nav-item"><a class="nav-link text-bg-info">{{ user.username }}</a></li>
                {% if user.Empleado.avatar.url %}
                    <li class="nav-item"> <img src="{{ user.Empleado.avatar.url }}" alt="avatar" class="" style="height: 30px;"></li>
                    {% else %}
                    <li class="nav-item"> <img src="{% static 'Usuarios/usuarios.png' %}" alt="avatar" class="" style="height: 30px;"></li>
                {% endif %}  
                <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:logout' %}">Logout</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link {% if request.path == "/about/" %} active  {% endif %}" href="{% url 'Home:about' %}">Sobre nosotros</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == "/contacto/" %} active  {% endif %}" href="#">Contacto</a></li>
                <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>

project/apps/Home/templates/Home/register.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Registro de usuario
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3"> 
            <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
        </div>
    </form>

{% endblock INDEX_CONTENIDO %}