project/apps/Producto/urls.py
from django.urls import path

from . import views

app_name = "Producto"

urlpatterns = [path("", views.index, name="home")]

urlpatterns += [
    path("ubicacion/list/", views.UbicacionList.as_view(), name="ubicacion_list"),
    path("ubicacion/create/", views.UbicacionCreate.as_view(), name="ubicacion_create"),
    path("ubicacion/detail/<int:pk>", views.UbicacionDetail.as_view(), name="ubicacion_detail"),
    path("ubicacion/update/<int:pk>", views.UbicacionUpdate.as_view(), name="ubicacion_update"),
    path("ubicacion/delete/<int:pk>", views.UbicacionDelete.as_view(), name="ubicacion_delete"),
]

urlpatterns += [
    path("cilindro/list/", views.CilindroList.as_view(), name="cilindro_list"),
    path("cilindro/create/", views.CilindroCreate.as_view(), name="cilindro_create"),
    path("cilindro/detail/<int:pk>", views.CilindroDetail.as_view(), name="cilindro_detail"),
    path("cilindro/update/<int:pk>", views.CilindroUpdate.as_view(), name="cilindro_update"),
    path("cilindro/delete/<int:pk>", views.CilindroDelete.as_view(), name="cilindro_delete"),
]

urlpatterns += [
    path("salida/list/", views.CilindroList.as_view(), name="salida_list"),
    path("salida/create/", views.CilindroCreate.as_view(), name="salida_create"),
    path("salida/detail/<int:pk>", views.CilindroDetail.as_view(), name="salida_detail"),
    path("salida/update/<int:pk>", views.CilindroUpdate.as_view(), name="salida_update"),
    path("salida/delete/<int:pk>", views.CilindroDelete.as_view(), name="salida_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("Producto/", include("Producto.urls")),
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/Producto/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

# Create your models here.


class Ubicacion(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    direccion = models.CharField(max_length=200)
   
    def __str__(self):
        return f'{self.nombre} {self.direccion}'

class Cilindro(models.Model):
    numero_serie = models.CharField(max_length=100, unique=True)
    tipo_gas = models.CharField(max_length=50)
    capacidad = models.IntegerField()
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE) 
    fecha_ingreso = models.DateTimeField(
        default=timezone.now, verbose_name="fecha de ingreso") 
    
    def __str__(self) -> str:
        return f"{self.numero_serie} {self.tipo_gas}{self.ubicacion}"
    
    class Meta:
        verbose_name = "cilindro"
        verbose_name_plural = "cilindros"
        
class Salida(models.Model):
    numero_serie = models.CharField(max_length=100, unique=True)
    tipo_gas = models.CharField(max_length=50)
    capacidad = models.IntegerField()
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE) 
    fecha_salida = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ("-fecha_salida",)

    def clean(self):
        if self.capacidad > self.numero_serie.capacidad:
            raise ValidationError("Sin stock, producto no se encuentra en inventario")

project/apps/Producto/forms.py
from django import forms
from .models import Cilindro, Ubicacion, Salida

class CilindroForm(forms.ModelForm):
    class Meta:
        model = Cilindro
        fields = ['numero_serie', 'tipo_gas', 'capacidad', 'ubicacion', 'fecha_ingreso']


class UbicacionForm(forms.ModelForm):
    class Meta:
        model = Ubicacion
        fields = ['nombre', 'direccion']


class SalidaForm(forms.ModelForm):
    class Meta:
        model = Salida
        fields = "__all__"

project/apps/Producto/views.py
from django.shortcuts import render
from typing import Any
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models


@login_required
def index(request):
    return render(request, "Producto/index.html")



class UbicacionList(ListView):
    model = models.Ubicacion

class UbicacionCreate(CreateView):
    model = models.Ubicacion
    form_class = forms.UbicacionForm
    success_url = reverse_lazy("Producto:ubicacion_list")

class UbicacionDetail(DetailView):
    model = models.Ubicacion

class UbicacionUpdate(UpdateView):
    model = models.Ubicacion
    form_class = forms.UbicacionForm
    success_url = reverse_lazy("Producto:ubicacion_list")

class UbicacionDelete(DeleteView):
    model = models.Ubicacion
    success_url = reverse_lazy("Producto:ubicacion_list")

#CILINDROS
class CilindroList(ListView):
    model = models.Cilindro

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Cilindro.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Cilindro.objects.all()
        return object_list


class CilindroCreate(CreateView):
    model = models.Cilindro
    form_class = forms.CilindroForm
    success_url = reverse_lazy("Producto:cilindro_list")


class CilindroDetail(DetailView):
    model = models.Cilindro


class CilindroUpdate(UpdateView):
    model = models.Cilindro
    form_class = forms.CilindroForm
    success_url = reverse_lazy("Producto:cilindro_list")


class CilindroDelete(DeleteView):
    model = models.Cilindro
    success_url = reverse_lazy("Producto:cilindro_list")


class CilindroList(ListView):
    model = models.Cilindro

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Cilindro.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Cilindro.objects.all()
        return object_list

#SALIDA
class SalidaCreate(CreateView):
    model = models.Salida
    form_class = forms.SalidaForm
    success_url = reverse_lazy("Producto:salida_list")


class SalidaDetail(DetailView):
    model = models.Salida


class SalidaUpdate(UpdateView):
    model = models.Salida
    form_class = forms.SalidaForm
    success_url = reverse_lazy("Producto:salida_list")


class SalidaDelete(DeleteView):
    model = models.Salida
    success_url = reverse_lazy("Producto:salida_list")

project/apps/Producto/templates/Producto/cilindro_confirm_delete.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Eliminación de Cilindros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/cilindro_create.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Crear Cilindros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>
    
    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/cilindro_detail.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Detalle de Cilindros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <ul>
        <li>numero_serie: {{ object.numero_serie }} </li>
        <li>tipo_gas: {{ object.tipo_gas }} </li>
        <li>capacidad: {{ object.capacidad }} </li>
        <li>ubicacion: {{ object.ubicacion }} </li>
        <li>fecha_ingreso: {{ object.fecha_ingreso}} </li>
    </ul>

    {% include 'Home/index_back.html' %}
    
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/cilindro_form.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Crear Cilindros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
<h1 class="text-center">INGRESA UN NUEVO CILINDRO</h1>
<!-- Etiqueta Formulario -->
<div class="bg-black text-warning formulario text-center ">
    <style>
        .formulario{
            padding: 50px;
            width: 95%;
            margin: 25px;
        }
    </style>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}} 
        <button class="btn btn-danger" type="submit">Guardar</button>
</div>
    
    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/cilindro_list.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Listado de Cilindros 
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    {% if object_list %}

        <div>
            <form action="{% url 'Producto:cilindro_list' %}" method="get">
                <input type="text" name="consulta" placeholder="Buscar...">
            </form>
        </div>

        {% for object in object_list %}
            <ul>
                <li>{{ object.numero_serie }} {{ object.tipo_gas }}
                    <a href="{% url 'Producto:cilindro_detail' object.id %}" class="btn btn-secondary btn-sm">
                        Ver detalle</a>
                    <a href="{% url 'Producto:cilindro_update' object.id %}" class="btn btn-primary  btn-sm">
                        Actualizar</a>
                    <a href="{% url 'Producto:cilindro_delete' object.id %}" class="btn btn-danger  btn-sm">
                        Eliminar</a>
                </li>
            </ul>
        {% endfor %}        
    {% else %}
        <p class="fs-4 fst-italic ">No hay cilindros ingresados</p>
    {% endif %}


    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/index.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %} 
    Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <h3 class="pb-lg-3 ">
        Ubicacion de los Cilindros
    </h3>
    
    <div class="d-grid gap-3 ">  
        {% if user.is_staff %}
            <a href="{% url 'Producto:ubicacion_create' %}" class="btn btn-primary ">Crear Ubicacion</a>
            <br>
        {% endif %}
        <a href="{% url 'Producto:ubicacion_list' %}" class="btn btn-primary ">Listar ubicaciones de los Cilindros</a>
        <br>
    </div>
    
    <h3 class="pb-lg-3 ">
        Cilindros
    </h3>
    
    <div class="d-grid gap-3 ">  
        {% if user.is_staff %}
            <a href="{% url 'Producto:cilindro_create' %}" class="btn btn-primary ">Crear Cilindro</a>
            <br>
        {% endif %}
        <a href="{% url 'Producto:cilindro_list' %}" class="btn btn-primary ">Listar Cilindros</a>
        <br>
    </div>

    <h3 class="pb-lg-3 ">
        Salidas 
    </h3>
    
    <div class="d-grid gap-3 ">  
        {% if user.is_staff %}
            <a href="{% url 'Producto:salida_create' %}" class="btn btn-primary ">Crear Salida</a>
            <br>
        {% endif %}
        <a href="{% url 'Producto:salida_list' %}" class="btn btn-primary ">Listar Salidas</a>
        <br>
    </div>


    {% include 'Home/index_back.html' %}

{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/salida_confirm_delete.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Eliminación Salida
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/salida_detail.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Detalle de Salida de Cilindros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <ul>
        <li>numero_serie: {{ object.numero_serie }} </li>
        <li>tipo_gas: {{ object.tipo_gas }} </li>
        <li>capacidad: {{ object.capacidad }} </li>
        <li>ubicacion: {{ object.ubicacion }} </li>
        <li>fecha_salida: {{ object.fecha_salida}} </li>
    </ul>

    {% include 'Home/index_back.html' %}
    
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/salida_form.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Crear/Actualizar 
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
<h1 class="text-center">INGRESA UN NUEVA SALIDA</h1>
<!-- Etiqueta Formulario -->
<div class="bg-black text-warning formulario text-center ">
    <style>
        .formulario{
            padding: 50px;
            width: 95%;
            margin: 25px;
        }
    </style>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}} 
        <button class="btn btn-danger" type="submit">Guardar</button>
</div>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/salida_list.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Listado de salidas ingresadas
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    {% if object_list %}

        {% for object in object_list %}
            <ul>
                <li>{{ salida.numero_serie }}
            
                    <a href="{% url 'Producto:salida_detail' object.id %}">Ver detalle</a>
                    <a href="{% url 'Producto:salida_update'  object.id%}">Actualizar</a>
                    <a href="{% url 'Producto:salida_delete' object.id %}">Eliminar</a>
                </li>
            </ul>
        {% endfor %}        
    {% else %}
        <p>no hay salidas ingresadas</p>

    {% endif %}


    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/ubicacion_confirm_delete.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Eliminación de la Ubicacion
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/ubicacion_create.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Crear/Actualizar Ubicacion
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/ubicacion_form.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Crear/Actualizar Ubicacion
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
<h1 class="text-center">INGRESA UN NUEVA UBICACIÓN</h1>
<!-- Etiqueta Formulario -->
<div class="bg-black text-warning formulario text-center ">
    <style>
        .formulario{
            padding: 50px;
            width: 95%;
            margin: 25px;
        }
    </style>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}} 
        <button class="btn btn-danger" type="submit">Guardar</button>
</div>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Producto/templates/Producto/ubicacion_list.html
{% extends 'Producto/index.html' %}

{% block INDEX_TITULO %} 
    Listado de ubicaciones 
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    {% if object_list %}

        {% for object in object_list %}
            <ul>
                <li>{{ ubicacion.nombre }}
            
                    <a href="{% url 'Producto:ubicacion_detail' object.id %}">Ver detalle</a>
                    <a href="{% url 'Producto:ubicacion_update'  object.id%}">Actualizar</a>
                    <a href="{% url 'Producto:ubicacion_delete' object.id %}">Eliminar</a>
                </li>
            </ul>
        {% endfor %}        
    {% else %}
        <p>no hay direcciones ingresadas</p>

    {% endif %}


    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}